### ISSUE TITLE
Icon for Big Sur

### ISSUE THREAD

**Issue by JDagsa** [vineetchoudhary/Downloader-for-Apple-Developers#14]
Hey, I made an icon for your app for Big Sur. I hope you would be able to use this!

This will also go to macosicons.com by elrumo (Elias Ruiz Montserrat, profile at https://www.github.com/elrumo)

### The icon
![Downloader_for_Apple_Developers](https://user-images.githubusercontent.com/72021139/99189726-7b7bed00-279d-11eb-8caf-9ff87c8f68df.png)

**Comment by JDagsa** [comment]
The picture's in PNG, just make .iconset for the icon, then go use iconutil to convert iconset:

```
iconutil -c icns /Path/To/Icon.iconset
```

*Note: Replace /Path/To/Icon.iconset with the path to the iconset*

Hope you can use it! Thanks!

**Comment by vineetchoudhary** [comment]
Added in the latest version. Thanks, guys.
