### ISSUE TITLE
It appears that "More Downloads" UI has changed and the software broke...

### ISSUE THREAD

**Issue by isaac-weisberg** [vineetchoudhary/Downloader-for-Apple-Developers#16]
"More Downloads" at the Apple Developer Downloads page now looks drastically different, and the legacy page doesn't appear no more.

Clicking on Download for Xcode 12.4 doesn't do anything, the download doesn't start.

**Comment by McLeroy** [comment]
Looking at the Logs: Downloader -> File -> Logs -> Show in Console App. 

`_Output Stream - Error - download authentication token not found. Press ⌘+R to get updated token._`

**Comment by vineetchoudhary** [comment]
I think this new "More Downloads" page breaks the downloading process. I'm looking into it.

**Comment by vineetchoudhary** [comment]
Hi, This issue has been fixed. Please update to the latest [version](https://github.com/vineetchoudhary/Downloader-for-Apple-Developers/releases/tag/2.1.0).
