### ISSUE TITLE
Add information about how it works on the README file

### ISSUE THREAD

**Issue by rogerluan** [vineetchoudhary/Downloader-for-Apple-Developers#19]
This would be very convenient :) I'm interested in learning how this works internally without necessarily digging into the code 😁 

Great utility, thanks!

**Comment by marlonjames71** [comment]
Thank you! I completely agree this should be added!

**Comment by vineetchoudhary** [comment]
Hi, There is a thanks section in [README](https://github.com/vineetchoudhary/Downloader-for-Apple-Developers#thanks), and that includes what it use to make download faster. So, basically, this is completely dependent on [aria2](https://github.com/aria2/aria2). aria2 is a utility for downloading files that support segmented downloading. When we start downloading this program take the Download Auth token from cookies and other requires params and pass them to aria2. 

An instance of [Process](https://developer.apple.com/documentation/foundation/process) takes the output from aira2 and shows it on UI. So, you can do the same with aria2 without this program but you have manually taken out the Auth Token from cookies and other variables like URL. You can take look at the [scripts](https://github.com/vineetchoudhary/Downloader-for-Apple-Developers/tree/master/Downloader/Scripts) file.

**Comment by marlonjames71** [comment]
Thanks for sharing that and clearing that up!
