### ISSUE TITLE
The latest version of the software cannot be used normally and will crash

### ISSUE THREAD

**Issue by snowasnow** [vineetchoudhary/Downloader-for-Apple-Developers#20]
platform: MacBook Pro (M1)
os: macOS big sur 11.4
software version: 2.1(1)

When I log in with my Apple Developer Account and select any file to start the download. Downloader immediately crashed. 
2021/06/22 09:20:42:397  Downloader Started.
2021/06/22 09:20:42:485  Downloader Finish Launching.
2021/06/22 09:20:46:428  Navigation Status - Login is required to access this page.
2021/06/22 09:21:16:565  Decided download for extension = - xip
2021/06/22 09:21:16:566  Output Stream - Error - download authentication token not found. Press ⌘+R to get updated token.

**Comment by mengshun** [comment]
me too

**Comment by ParkerRex** [comment]
mine doesn't crash but makes zero progress on downloads...

**Comment by ParkerRex** [comment]
> mine doesn't crash but makes zero progress on downloads...

jk. it's working.

**Comment by vineetchoudhary** [comment]
Hi, Sorry for the late reply. I'm not able to reproduce it on multiple systems. Please double check you are using the latest version.

**Comment by tmcarr** [comment]
I just reproduced this.

**Comment by levidjones** [comment]
Just downloaded the latest version and I also have this as a recurring issue on M1 iMac OSX Monterey

I'd be happy to share logs or hop on a chat and show you if you need it @vineetchoudhary

**Comment by timothycosta** [comment]
I hit the same issue on my M1. Running it under Rosetta avoids the crash.

**Comment by vineetchoudhary** [comment]
Hi, I got the crash report and looks like this mostly happens on M1. I'll add a possible fix but as I don't have M1 MacBook so can some help me to verify it?

**Comment by timothycosta** [comment]
@vineetchoudhary of course. :+1:

**Comment by vineetchoudhary** [comment]
@timothycosta can you please check this build - 

[Downloader.zip](https://github.com/vineetchoudhary/Downloader-for-Apple-Developers/files/6917918/Downloader.zip)

**Comment by timothycosta** [comment]
@vineetchoudhary Worked great!

**Comment by vineetchoudhary** [comment]
Fixed in the latest release.
