### ISSUE TITLE
CleanMyMac X reports potential threat for Downloader.app

### ISSUE THREAD

**Issue by twiedow** [vineetchoudhary/Downloader-for-Apple-Developers#25]
CleanMyMac X keeps telling me that Downloader.app is a potential threat  and contains a backdoor (see screenshot). Does anybody why this happens?

![Screenshot 2021-11-10 at 16 07 49](https://user-images.githubusercontent.com/656549/141138755-9a4fe487-f819-4800-af21-94bcfa7cb8ca.png)

**Comment by vineetchoudhary** [comment]
That is strange. I just performed the online scan which scans the file using different antivirus software and all show "found nothing". Do CleanMyMac provide more details about this?
<img width="1176" alt="Screenshot 2021-11-10 at 9 10 34 PM" src="https://user-images.githubusercontent.com/8479436/141144582-c990ccf8-1f1d-4cc4-b9f9-77b1a66d09c9.png">

**Comment by vineetchoudhary** [comment]
One reason might be "WebKit". As it is showing WebKit as trojan and "Downloader.app" also uses the WebKit to load the Apple Download page so that might be the reason.

**Comment by JJTech0130** [comment]
I was a little worried about this, but [VirusTotal](https://www.virustotal.com/gui/file/bd38af9d49337e4fb6abe196156f1de7690280885e29f247625a82610bad0414/summary) says it’s clean so I think it’s fine.

**Comment by vineetchoudhary** [comment]
Thanks, @JJTech0130.
