### ISSUE TITLE
co.di.downloader marked as a backdoor by cleanmymac

### ISSUE THREAD

**Issue by BentEngbers** [vineetchoudhary/Downloader-for-Apple-Developers#27]
I have been using your application to download and reinstall xcode (multiple times), and i must say, the speedup is incredible! 
When i ran [cleanmymac](https://cleanmymac.macpaw.com/) malware removal, it reported that this application `co.di.downloader` was marked as a backdoor. 
While I believe that downloader is not malicious, i was wondering why it was marked as a backdoor.
This identification could potentially discourage users to use this application, which would be a shame.
Thank you for developing this awesome application!

**Comment by vineetchoudhary** [comment]
Hi @BentEngbers 

Thank you for using the application. We already discussed this issue here here - https://github.com/vineetchoudhary/Downloader-for-Apple-Developers/issues/25

If this time cleanmymac provide different report than please share.
