### ISSUE TITLE
Can't login with 2FA

### ISSUE THREAD

**Issue by elmoritz** [vineetchoudhary/Downloader-for-Apple-Developers#4]
I tried to login in and i receive the prompt to accept the new login location with the follow 6 digit number, BUT there is no place to fill it in.
I do get the numbers but the usual form where you have to accept the 2FA is not showing up.

otherwise great idea.

**Comment by vineetchoudhary** [comment]
Hi @elmoritz ,

This should not be happen. Because it just a WKWebView which open apple authorisation page. Can you please provide the logs. You can see the logs generated by Downloader in `File>Logs>Show in Finder` or `⌘`+`F`.

**Comment by elmoritz** [comment]
Hi @vineetchoudhary,
the issue resolved itself. tried it over the weekend without any luck, when i received your message I went through the process again and the page magically appeared.

thank you for your quick answer
