### ISSUE TITLE
Navigation Error - An SSL error

### ISSUE THREAD

**Issue by KenjutsuGH** [vineetchoudhary/Downloader-for-Apple-Developers#6]
I keep getting this error:

2020/07/29 11:27:06:045  Downloader Started.
2020/07/29 11:27:06:405  Downloader Finish Launching.
2020/07/29 11:27:11:983  Navigation Error - An SSL error has occurred and a secure connection to the server cannot be made.
2020/07/29 11:29:47:468  Source Status - Please wait. Loading Videos (WWDC, Tech Talks, etc.) page...
2020/07/29 11:29:51:707  Navigation Status - You're all set. Start Downloading.
2020/07/29 11:29:56:994  Navigation Status - You're all set. Start Downloading.
2020/07/29 11:30:04:195  Source Status - Please wait. Loading Tools (Xcode, macOS, etc.) page...
2020/07/29 11:30:07:429  Navigation Error - An SSL error has occurred and a secure connection to the server cannot be made.
2020/07/29 11:30:28:334  Navigation Error - An SSL error has occurred and a secure connection to the server cannot be made.

macOS: 10.13.6

**Comment by vineetchoudhary** [comment]
Hi @KenjutsuGH,

Are you able to visit this url https://developer.apple.com/download/more/ in safari browser without any problem?

**Comment by KenjutsuGH** [comment]
Hi,

No, I get "Safari can't establish a secure connection".

I does, however, load using Chrome

**Comment by vineetchoudhary** [comment]
Hi,

Thanks for the information. Looks like this is a very common problem but can be due to n number of reasons. You can search this error on google there are lots of different solutions to this problem you can try those.
